export const MAX_CUSTOMERS = 10;

export const TabInfo = {
  CUSTOMER_SEARCH: {
    id: 0,
    label: '고객조회',
  },
  SERVICE_MODIFICATION: {
    id: 1,
    label: '요금제/부가서비스 변경',
  },
  NEW_SUBSCRIPTION: {
    id: 2,
    label: '신규가입',
  },
} as const;

export const DEFAULT_TABS = [
  { id: 0, label: TabInfo.CUSTOMER_SEARCH.label, closeable: false },
  { id: 1, label: TabInfo.SERVICE_MODIFICATION.label, closeable: true },
  { id: 2, label: TabInfo.NEW_SUBSCRIPTION.label, closeable: true },
];

export const SUBSCRIPTION_MENUS = [
  { id: 'NEW_SUBSCRIPTION', name: TabInfo.NEW_SUBSCRIPTION.label },
  { id: 'SERVICE_MODIFICATION', name: TabInfo.SERVICE_MODIFICATION.label },
];

export enum MainMenu {
  HOME = 'home',
  MENU = 'menu',
  BOOKMARKS = 'bookmarks',
  CUSTOMERS = 'customers',
}

export const ROLE_SEARCH_TEL_NO = 'ROLE_SEARCH_TEL_NO';
export const ROLE_UNMASKING = 'ROLE_UNMASKING';

export const AUTH_PHONE_NUMBER_LOOKUP = 'ROLE_SEARCH_TEL_NO';
export const AUTH_UNMASKING = 'ROLE_UNMASKING';

export enum MASKING_ITEM_CODE {
  CUSTOMER_NAME = 'CUSTOMER_NAME',
  CUSTOMER_RRNO = 'CUSTOMER_RRNO',
  CUSTOMER_DRIVERSLICENSENUMBER = 'CUSTOMER_DRIVERSLICENSENUMBER',
  CUSTOMER_FOREIGNERSNUMBER = 'CUSTOMER_FOREIGNERSNUMBER',
  CUSTOMER_PASSPORTNUMBER = 'CUSTOMER_PASSPORTNUMBER',
  CUSTOMER_PHONENUMBER = 'CUSTOMER_PHONENUMBER',
  CUSTOMER_ACCOUNTNUMBER = 'CUSTOMER_ACCOUNTNUMBER',
  CUSTOMER_CREDITCARDNUMBER = 'CUSTOMER_CREDITCARDNUMBER',
  CUSTOMER_CREDITCARDVALIDDATE = 'CUSTOMER_CREDITCARDVALIDDATE',
  CUSTOMER_ADDRESS = 'CUSTOMER_ADDRESS',
  CUSTOMER_EMAIL = 'CUSTOMER_EMAIL',
  CUSTOMER_ALLMASKINGINFO = 'CUSTOMER_ALLMASKINGINFO',
}
