export const MAX_CUSTOMERS = 10;

export const DEFAULT_TABS = [
  { id: 0, label: '고객조회', closeable: false },
  { id: 1, label: '요금제/부가서비스 변경', closeable: true },
  { id: 2, label: '신규가입', closeable: true },
];

export const SUBSCRIPTION_MENUS = [
  { id: 'NEW_SUBSCRIPTION', name: '신규가입' },
  { id: 'SERVICE_MODIFICATION', name: '요금제/부가서비스 변경' },
];

export enum MainMenu {
  HOME = 'home',
  MENU = 'menu',
  BOOKMARKS = 'bookmarks',
  CUSTOMERS = 'customers',
}

export const ROLE_SEARCH_TEL_NO = 'ROLE_SEARCH_TEL_NO';
export const ROLE_UNMASKING = 'ROLE_UNMASKING';

export const AUTH_PHONE_NUMBER_LOOKUP = 'ROLE_SEARCH_TEL_NO';
export const AUTH_UNMASKING = 'ROLE_UNMASKING';

export enum MASKING_ITEM_CODE {
  CUSTOMER_NAME = 'CUSTOMER_NAME',
  CUSTOMER_RRNO = 'CUSTOMER_RRNO',
  CUSTOMER_DRIVERSLICENSENUMBER = 'CUSTOMER_DRIVERSLICENSENUMBER',
  CUSTOMER_FOREIGNERSNUMBER = 'CUSTOMER_FOREIGNERSNUMBER',
  CUSTOMER_PASSPORTNUMBER = 'CUSTOMER_PASSPORTNUMBER',
  CUSTOMER_PHONENUMBER = 'CUSTOMER_PHONENUMBER',
  CUSTOMER_ACCOUNTNUMBER = 'CUSTOMER_ACCOUNTNUMBER',
  CUSTOMER_CREDITCARDNUMBER = 'CUSTOMER_CREDITCARDNUMBER',
  CUSTOMER_CREDITCARDVALIDDATE = 'CUSTOMER_CREDITCARDVALIDDATE',
  CUSTOMER_ADDRESS = 'CUSTOMER_ADDRESS',
  CUSTOMER_EMAIL = 'CUSTOMER_EMAIL',
  CUSTOMER_ALLMASKINGINFO = 'CUSTOMER_ALLMASKINGINFO',
}
