#!/bin/sh
# Unix/Linux/Mac의 경우
# chmod +x .husky/pre-commit

# Windows의 경우 (Git Bash 사용)
# git update-index --chmod=+x .husky/pre-commit

echo "Husky is Running!"

# Get current branch name
BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

# Check branch name format
if ! echo "$BRANCH_NAME" | grep -qE '^(feature|bugfix)/KAN-[0-9]+-[a-zA-Z0-9-]+$'; then
    echo "Error: Branch name must follow the format 'feature/KAN-{number}-{content}' or 'bugfix/KAN-{number}-{content}'"
    echo "Current branch name: $BRANCH_NAME"
    exit 1
fi

echo "Branch name validation passed!"

# Get commit message
if [ -n "$1" ]; then
    # If message is passed via file (git commit without -m)
    COMMIT_MSG=$(cat "$1")
else
    # If message is passed via -m or -am option
    COMMIT_MSG=$(git log -1 --pretty=%B)
fi

# Check commit message format
#if ! echo "$COMMIT_MSG" | grep -qE '^KAN-[0-9]+[[:space:]].+$'; then
#    echo "Error: Commit message must follow the format 'KAN-{number} {content}'"
#    echo "Content can include Korean, English, numbers, and spaces"
#    echo "Current commit message: $COMMIT_MSG"
#    exit 1
#fi

echo "Commit message validation passed!"
echo "Code format and ESLint"
npm run lint
npm run format
echo "End of Code format and ESLint"